In [1]:
# list 4-1-1
import numpy as np

In [2]:
# list 4-1-2
a = np.array([2, 1])
print(a)

[2 1]


In [3]:
# list 4-1-3
type(a)

numpy.ndarray

In [4]:
# list 4-1-4
c = np.array([[1, 2], [3, 4]])
print(c)

[[1 2]
 [3 4]]


In [5]:
# list 4-1-5
d = np.array([[1], [2]])
print(d)

[[1]
 [2]]


In [6]:
# list 4-1-6
print(d.T)

[[1 2]]


In [7]:
# list 4-1-7
a = np.array([2, 1])
b = np.array([1, 3])
print(a + b)

[3 4]


In [8]:
# list 4-1-8
a = np.array([2, 1])
b = np.array([1, 3])
print(a - b)

[ 1 -2]


In [9]:
# list 4-1-9
print(2 * a)

[4 2]


In [10]:
# list 4-1-10
b = np.array([1, 3])
c = np.array([4, 2])
print(b.dot(c))

10


In [11]:
# list 4-1-11
a = np.array([1, 3])
print(np.linalg.norm(a))

3.1622776601683795
